### ISSUE TITLE
Feature Parity Macro-ticket

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#3273]
Macro-ticket for various cores able to completely obsolete the use of an older core once feature parity is met. The older core should be removed feature parity is achieved. This hopefully can give a checklist of things to do to reach feature parity and help trim out these cores.

BSNES -> BSNESv115
Not sure what's missing here exactly? @Morilli

Octoshock -> Nymashock
- [ ] Standard debugging features (get/set regs, mem callbacks, tracelogging, disassembly) (re: https://github.com/TASEmulators/BizHawk/issues/3141)
- [ ] Non-disc loading (EXE/PSF)
- [ ] Resolution management options
- [ ] Deinterlacing options (see https://github.com/TASEmulators/BizHawk/issues/3196)
- [ ] GPU Lag Frames

PCEHawk -> TurboNyma
- [ ] Standard debugging features (get/set regs, mem callbacks, tracelogging, disassembly, code data logger) (re: https://github.com/TASEmulators/BizHawk/issues/3141)
- [ ] Sound debugger (re: https://github.com/TASEmulators/BizHawk/issues/2054)

Might be missing something here, feel free to addon anything.

**Comment by Morilli** [comment]
> BSNES -> BSNESv115
Not sure what's missing here exactly?

If I remember correctly, the only missing things would be support for the Code-Data-Logger (which I didn't put in because it seemed like high expense for low functionality gain) and the SNES graphics debugger (which does have a [branch](https://github.com/TASEmulators/BizHawk/tree/bsnes-gfx-debugger), but it isn't quite... completed).
