### ISSUE TITLE
Lua testing for 2.9

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3485]
- [x] integers
	- [x] migration snippet for `bit`: `bit = (require "migration_helpers").EmuHawk_pre_2_9_bit();`
- [x] `userdata.get_keys`
- [x] `bizstring.pad_{start,end}`
- [x] `event.on_bus_{read,write,exec,exec_any}` with parameters and `event.can_use_callback_params("memory")`
	- [x] still need to document what the parameters are
- [ ] `movie.play_from_start` (restart)
- [ ] `movie.play_from_start` (load)
- [x] colour parsing

**Comment by CasualPokePlayer** [comment]
>  `event.on_bus_{read,write,exec,exec_any}` with parameters and `event.can_use_callback_params("memory")`
> `movie.play_from_start` (restart)

These seem to work perfectly fine in testing.
>  `movie.play_from_start` (load)

This works fine (tested both absolute and relative movie locations). I would note though the current directory in this case is .exe dir (lua console) or script dir (script loaded), rather than the (possibly expected?) movie dir. Similar cases can be applied to other things so not too concerning.

**Comment by YoshiRulz** [comment]
Can we add to `LUA_PATH`? I want to be able to write `bit = require "EmuHawk-2_8-bit";` instead of `bit = require "../migration_helpers/EmuHawk-2_8-bit.lua";`, which users can't copy-paste into their scripts without modification.

**Comment by CasualPokePlayer** [comment]
We can modify `package["path"]` I assume. Although on that note, I see the lua dir in there for me, so I assume this isn't actually an issue?

**Comment by YoshiRulz** [comment]
No luck.
```
NLua.Exceptions.LuaScriptException: [string "main"]:4: module 'migration_helpers' not found:
	no field package.preload['migration_helpers']
	no file '/usr/local/share/lua/5.4/migration_helpers.lua'
	no file '/usr/local/share/lua/5.4/migration_helpers/init.lua'
	no file '/usr/local/lib/lua/5.4/migration_helpers.lua'
	no file '/usr/local/lib/lua/5.4/migration_helpers/init.lua'
	no file './migration_helpers.lua'
	no file './migration_helpers/init.lua'
	no file '/usr/local/lib/lua/5.4/migration_helpers.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './migration_helpers.so'
```
`require "migration_helpers"` *does* work if the lib is placed beside the calling script, but then `require "../migration_helpers.lua"` doesn't work when it's placed above the calling script.

**Comment by CasualPokePlayer** [comment]
What does `print(package["path"])` output for you?

fwiw it seems that for me I can place some lua file in BizHawk's lua dir and require it just fine (of course the lua file doing the require outside of the lua dir here, so it's not looking in the same directory)

**Comment by YoshiRulz** [comment]
`/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua`

**Comment by CasualPokePlayer** [comment]
Ok then it's weirdly not setting the lua dir in there then for some reason (some difference between Windows and Linux I guess). It wouldn't be too hard to just do some lua code to force the lua path to be added.

**Comment by CasualPokePlayer** [comment]
See if <https://github.com/CasualPokePlayer/BizHawk/commit/c809f1c8c351351313acd60c6b9ea44caa2eae72> makes the require work.

**Comment by kalimag** [comment]
Perhaps cbb335fec24267f2f560d376154cb14265be8998 should also apply to Windows so it stays consistent with `PathEntries`? I think Lua just defaults to `<current dir>\lua` on Windows which happens to match BizHawk's default Lua path.

**Comment by ISSOtm** [comment]
I don't know if this is the right place to post this, but I have the following issue:

![image](https://user-images.githubusercontent.com/15271137/208194859-dd5ed501-4fd6-46e9-80c6-5dbf4e647d35.png)

It looks like the Lua search path ignores the system directories?

**Comment by ISSOtm** [comment]
After committing the slight crime of `ln -s /usr/lib/lua /usr/local/lib/lua`, I now get this:

![image](https://user-images.githubusercontent.com/15271137/208195218-c717fb57-1348-4ecc-8077-2f9ad9c538f2.png)

**Comment by CasualPokePlayer** [comment]
Try deleting the liblua54.so in our dll folder and see that forces your own distro provided lua to be used.

**Comment by YoshiRulz** [comment]
Proper fix would be to set `LUA_PATH` as we discussed above.

**Comment by CasualPokePlayer** [comment]
I don't think that would fix the dynamic libraries not being enabled issue (and even then, changing lua path at most should be at most adding a path to our lua dir).

**Comment by ISSOtm** [comment]
> Try deleting the liblua54.so in our dll folder and see that forces your own distro provided lua to be used.

The error persists just the same.

**Comment by CasualPokePlayer** [comment]
Does it still have the pathing issues? (which wtf?). Or is it only the dynamic libraries issue (which seems bad but kinda hard to fix? Suppose BizHawk could try to provide its own self-built liblua54.so, although I would fear of potential conflicts with the system lua lib and mucking with the path anymore than we do now would be yikes.) The optimal solution is telling users to build themselves and make sure dynamic library support is enabled, but that's not really user friendly)

**Comment by ISSOtm** [comment]
I had removed `lua54.dll`, but not `liblua54.so`. Removing *that* makes the Lua console pop up an error box:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at BizHawk.Client.EmuHawk.LuaConsole.AskSaveChanges () [0x00006] in <379895d8d226489aa5b7e4a994e284eb>:0 
(snip)
```

**Comment by YoshiRulz** [comment]
Misleading secondary crash (I thought I fixed that?), check stdout for the first exception.

**Comment by ISSOtm** [comment]
```
System.DllNotFoundException: lua54 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) KeraLua.NativeMethods.luaL_newstate()
(snip)
```

**Comment by CasualPokePlayer** [comment]
To be clear the lua54.dll is the *native* dll for lua, so it's only usable on Windows. I'm guessing then it's not able to find your own liblua so (I assume it's due to the nonstandard naming? I'm guessing your own system has its lua so named as liblua.so.5.4?)

**Comment by ISSOtm** [comment]
```
lua /usr/lib/liblua.so
lua /usr/lib/liblua.so.5.4
lua /usr/lib/liblua.so.5.4.4
lua /usr/lib/liblua5.4.so
```

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/commit/339915c013829bf1246f6f5d64d7b89fe9735733
This should hopefully properly use the system lua 5.4. Sadly, CI is strained so there isn't any build available yet.

**Comment by ISSOtm** [comment]
Hmu when you got something for me to test, then

**Comment by YoshiRulz** [comment]
FFS I guess they decided to start enforcing Pull Mirroring being a paid feature. You can still push to the mirror.

**Comment by YoshiRulz** [comment]
Or just set a cron job

**Comment by CasualPokePlayer** [comment]
@ISSOtm Please try https://gitlab.com/TASVideos/BizHawk/-/jobs/3499656796/artifacts/download?file_type=archive

**Comment by DevreeseJorik** [comment]
The lua function `loadstring()` - see https://www.lua.org/manual/5.1/manual.html#pdf-loadstring
was removed in lua 5.2. Instead, it's functionality was added to `load', which now handles both chunks and strings - see http://www.lua.org/manual/5.2/manual.html#pdf-load

Suggesting `loadstring = load` to be added as an option in the migration handler?

**Comment by YoshiRulz** [comment]
`loadstring = load;` is already one line so there wouldn't be any benefit to having another migration helper function. (And why are you executing strings anyway, that's asking for trouble.)

**Comment by DevreeseJorik** [comment]
I was implementing a system in Lua that used keybinds to call functions on instances of a class. However, I encountered an issue where defining the functions within a table caused them to be immediately executed, rather than being stored as a reference to the function (as happens with regular functions by default). As a workaround, I used the loadstring function to execute the functions (stored as a string) when the corresponding keybind was pressed. 

Regardless, I can agree with it being too short.

**Comment by YoshiRulz** [comment]
@ISSOtm Did CPP's change fix your problem? Also, can you clarify whether it's a regression from 2.8, or works on Windows but not Linux, or whatever the case may be.

**Comment by ISSOtm** [comment]
Ah, uh, right. I'll need to test that soon, I didn't get notified of CPP's message fsr

**Comment by YoshiRulz** [comment]
bump
